export const RAIDS = [
  "Eater of Worlds",
  "Scourge of The Past",
  "Leviathan",
  "Spire of Stars",
  "Garden of Salvation",
  "Crown of Sorrow",
  "Last Wish",
]

export const GUARDIAN_CLASSES = ["Warlock", "Titan", "Hunter"]

export const CLASS_AFFINITY = ["Solar", "Void", "Arc"]

export const SUB_CLASSES = ["Top Tree", "Middle Tree", "Bottom Tree"]

export const TEAM_MODS = [
  "No HUD, Entire Team",
  "No Comms +Player",
  "No Mods, Entire Team",
]

export const ENCOUNTER_ROLLS = [
  "Triple Snipers",
  "Triple Grenade Launchers",
  "Triple Shotguns",
  "Triple Bows",
  "Double Side Arms, Any Heavy",
  "Double Auto Rifles, Any Heavy",
  "Double SMG's, Any Heavy",
  "Double Hand Cannons, Any Heavy",
  "All Blues",
  "All Blues +Exotic",
  "All Greens",
  "All Greens +Exotic",
  "Only Void weapons",
  "Only Arc weapons",
  "Only Solar weapons",
  "Only Abilites",
  "DIM Random loadout",
  "Only exotic weapon, Guardian choice",
  "Only exotic weapon +Exotic",
  "Full Auto Only, tape/hold down fire button",
  "Rainbow: White, Blue, Purple",
  "Only Close Range Weapons",
  "Only Long Range Weapons",
]

export const EXOTICS = [
  "Sweet Business",
  "Rat King",
  "Sturm",
  "The Jade Rabbit",
  "Cerberus+1",
  "Ace of Spades",
  "The Last Word",
  "Outbreak Perfected",
  "Monte Carlo",
  "Traveler's Chosen",
  "Mida Multi-Tool",
  "The Huckleberry",
  "Wish-Ender",
  "The Chaperone",
  "Arbalest",
  "Bad Juju",
  "Bastion",
  "Vigilance Wing",
  "Crimson",
  "SUROS Regime",
  "Malfeasance",
  "Izanagi's Burden",
  "Thorn",
  "Lumina",
  "Witherhoard",
  "Coldheart",
  "Graviton Lance",
  "Hard Light",
  "Prometheus Lens",
  "Trinity Ghoul",
  "Jotunn",
  "Eriana's Vow",
  "Devil's Ruin",
  "Ruinous Effigy",
  "Fighting Lion",
  "Skyburner's Oath",
  "Merciless",
  "Telesto",
  "Wavesplitter",
  "LeMonarque",
  "Divinity",
  "Tommy's Matchbook",
  "Sunshot",
  "Riskrunner",
  "Borealis",
  "Polaris Lance",
  "Lord of Wolves",
  "Tarrabah",
  "Symmetry",
  "The Fourth Horseman",
  "The Prospector",
  "D.A.R.C.I.",
  "Worldline Zero",
  "One Thousand Voices",
  "The Queenbreaker",
  "Truth",
  "Leviathan's Breath",
  "Tractor Cannon",
  "The Wardcliff Coil",
  "Sleeper Simulant",
  "Two-Tailed Fox",
  "Thunderlord",
  "Deathbringer",
  "Heir Apparent",
  "Legend of Acrius",
  "The Colony",
  "Whisper of the Worm",
  "Black Talon",
  "Anarchy",
  "Xenophage",
]

export const BASE_RAID = {
  name: "",
  guardians: [
    {
      name: "",
      class: "",
      affinity: "",
      subclass: "",
    },
    {
      name: "",
      class: "",
      affinity: "",
      subclass: "",
    },
    {
      name: "",
      class: "",
      affinity: "",
      subclass: "",
    },
    {
      name: "",
      class: "",
      affinity: "",
      subclass: "",
    },
    {
      name: "",
      class: "",
      affinity: "",
      subclass: "",
    },
    {
      name: "",
      class: "",
      affinity: "",
      subclass: "",
    },
  ],
  encounters: [],
}